name: "02_PR Workflow"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workloads/02-pr-workflow.yaml"
      - "samples/02-pr-workflow/**"
  pull_request:
    paths:
      - "samples/02-pr-workflow/**"
