name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  puppet-validate:
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Development
  
    steps:
      - uses: actions/checkout@v2
      - name: Install Puppet
        run: sudo apt install puppet
      - name: Run Puppet validation
        run: puppet parser validate site.pp
        working-directory: manifestruns-on: ubuntu-latest
