name: CI + CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

jobs:
  puppet-validate:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install Puppet
        run: sudo apt install puppet
      - name: Run Puppet validation
        run: puppet parser validate site.pp
        working-directory: manifest
